import React from "react";
import useLegendsService from "./Services/UseLegendsService";
import { LegendListProps } from "../Types/Types";

interface LegendDetailProps {
    legendKey: number;
}

export default function LegendDetail(props: LegendDetailProps) {
    const service = useLegendsService();

    if (service.status === 'loaded') {
        return (
            <>
                {/* {service.payload.map((legends: LegendListProps, key:any) => key == props.legendKey)} */}
                {service.payload.map((legends: LegendListProps, key:any) => (
                <>
                    {key == props.legendKey &&
                        <div key={key}>
                            {legends.name}
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                            <p>Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random v Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random RandomRandom Random Random Random Random Random Random Random Random Random Random Random Random Random Random Random</p>
                        </div>
                    }
                </>
            ))}

            </>
        );
    } else {
        return (<></>);
    }
};